# Generated by Django 3.2.5 on 2021-09-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entry_text',
            new_name='text',
        ),
    ]
